use_frameworks!
platform :ios, '10.0'

target 'FlatPageControlExample' do
    pod 'SwiftLint'
    pod 'FlatPageControl', :path => '../'

    target 'FlatPageControlExampleTests' do
        inherit! :search_paths
    end

end
