language: Swift
osx_image: xcode10
xcode_project: FlatPageControl.xcodeproj
xcode_scheme: FlatPageControl
before_install:
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true
script:
  - set -o pipefail
  - xcodebuild clean build -sdk iphonesimulator -project FlatPageControl.xcodeproj -scheme FlatPageControl CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild build test -scheme FlatPageControl -enableCodeCoverage YES -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=12.0' 
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'FlatPageControl'
