language: Swift
osx_image: xcode10
xcode_project: FlatPageControl.xcodeproj
xcode_scheme: FlatPageControl
before_install:
  - gem install xcpretty -N
script:
  - set -o pipefail
  - xcodebuild clean build -sdk iphonesimulator -project FlatPageControl.xcodeproj -scheme FlatPageControl CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild clean test -scheme FlatPageControl -configuration "Debug" -sdk iphonesimulator -enableCodeCoverage YES -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.4' | xcpretty -c 
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'FlatPageControl'
